## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('manet-routing-compare2-with-energy',
                                 ['wifi', 'dsr', 'dsdv', 'aodv', 'olsr', 'oplsr', 'internet', 'applications', 'energy', 'config-store', 'mobility'])
    obj.source = 'manet-routing-compare2-with-energy.cc'

